### ISSUE TITLE
Apparent failure for no apparent reason...

### ISSUE THREAD

**Issue by ben2talk** [catallo/ht#1]
![2023-12-29 08:49:58](https://github.com/catallo/ht/assets/6983154/13ea8f72-14d0-4b2b-97b6-201854bb5199)

After this:
 ```
./ht_2-3-6_linux_x64 -i                                                                                     
 🤖 ht is already installed and up to date.
```
ht shows red, non existent or not in path.

**Comment by catallo** [comment]
Could you let me know which shell you're using? 

And the output of
`ls ~/.config/ht/`

**Comment by ben2talk** [comment]
 config   ht   ht.bin

Fish terminal doesn't see the path, ht is red.
Zsh and Bash simply seem to work returning only the command entered:

**Comment by ben2talk** [comment]
![2023-12-29 10:07:55](https://github.com/catallo/ht/assets/6983154/4e30d0e2-cf53-4101-96d6-8cd0affc36e5)

**Comment by catallo** [comment]
It looks like there are two issues:

1. For some reason, 'ht' wasn't added to Fish's PATH. I recently tried installing 'ht' on a fresh Ubuntu setup, and adding it to Fish's PATH worked there. Did you close and reopen the shell after installing 'ht'? You can also manually set the PATH with the command: `set -Ua fish_user_paths ~/.config/ht/` (close and reopen shell afterwards)


2. There seems to be an issue with your OpenAI API key. Try setting it again using: `ht -set apikey <yourAPIkey>`

Note to myself: for the next release, add a function that checks if OpenAI key is valid.
